export const ENDPOINT = {
  SIGNUP: "/users/signup",
  LOGIN: "/users/login",
  GOOGLELOGINSIGNUP: "/users/gooleloginsignup",
  GETTOKEN: "/users/getrefreshtoken",
  PROFILE: "/users/profile",
  MSGSEND: "/users/msgsend",
  EMAILSEND: "/users/emailsend",
  RESETPASSWORD: "/users/resetpassword",
  GENERATENEWAPIKEY: "/users/generatenewapikey",
  UPDATEPROFILE: "/users/updateprofile",
  ADDDEPARTMENT: "/departments/add",
  UPDATEDEPARTMENT: "/departments/update",
  DEPARTMENTDETAIL: "/departments/detail",
  ADDPERSONNEL: "/personnels/add",
  UPDATEPERSONNEL: "/personnels/update",
  PERSONNELDETAIL: "/personnels/detail",
  ADDSTAFF: "/staffs/add",
  UPDATESTAFF: "/staffs/update",
  STAFFLIST: "/staffs/list",
};
